name: Java Maven Build

on:
  push:
    branches:
      - main  # or whatever your main branch is named
  pull_request:
    branches:
      - main  # or whatever your main branch is named

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Build with Maven
      run: mvn -B clean package

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: target/*.jar